---
- hosts: docker-deploy
  become: true
  tasks:
  - name: Install Docker
    package:
      name: docker
      state: present
  - name: Start Docker service
    service:
      name: docker
      state: started
  - name: create a container
    command: docker run -itd --name addressbook -p 8000:8000 haneef7/addressbook
